<a href="https://colab.research.google.com/github/amit1476/myUbuntuRep/blob/master/pyDS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%timeit sum(range(100))

The slowest run took 19.30 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 815 ns per loop


In [3]:
%%timeit
total = 0
for i in range(1000):
    for j in range(1000):
        total += i * (-1) ** j

1 loop, best of 3: 298 ms per loop


In [4]:
import random
L = [random.random() for i in range(100000)]
%timeit L.sort()

The slowest run took 24.35 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.24 ms per loop


In [5]:
import numpy as np

In [6]:
np.__version__

'1.18.5'

In [7]:
np?

In [8]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(l)

list

In [10]:
type(l[0])

int

In [11]:
l1 = list([1,2,3,'amit'])

In [12]:
l1

[1, 2, 3, 'amit']

In [13]:
type(l1[0])

int

In [14]:
type(l1[3])

str

In [15]:
l2 = [str(c) for c in l1]
l2

['1', '2', '3', 'amit']

In [16]:
[type(item) for item in l1]

[int, int, int, str]

In [17]:
import array as ar
A = ar.array('i', l)

In [18]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
type(A)

array.array

In [21]:
n1 = np.array(l, dtype='float32')
n1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [22]:
type(n1)

numpy.ndarray

In [23]:
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
#np.array(
[range(i,i+3) for i in [2,3,4]]
#)

[range(2, 5), range(3, 6), range(4, 7)]

In [25]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes


In [28]:
x2[0,1]

5

In [29]:
x2[0,1] = 12
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [30]:
x2[0,1] = 12.5224
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[:5]

array([0, 1, 2, 3, 4])

In [33]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x2[:2,]

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8]])

In [36]:
x2[:2,::3]

array([[3, 4],
       [7, 8]])

In [37]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2, 12,  3]])

In [38]:
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x2[0,:] # or x2[0]

array([ 3, 12,  2,  4])

In [40]:
x2_sub = x2[:2,:2]
x2_sub

array([[ 3, 12],
       [ 7,  6]])

In [41]:
x2_sub[0,0] = 100

In [42]:
x2_sub

array([[100,  12],
       [  7,   6]])

In [43]:
x2

array([[100,  12,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [44]:
x2_sub_copy = x2_sub.copy()
x2_sub_copy

array([[100,  12],
       [  7,   6]])

In [45]:
x2_sub_copy[0,0]= 20
x2_sub_copy

array([[20, 12],
       [ 7,  6]])

In [46]:
x2_sub

array([[100,  12],
       [  7,   6]])

In [49]:
x = np.array([1,2,3])
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [53]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [54]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [55]:
grid = np.array([[1,2],
                 [3,4]])
grid

array([[1, 2],
       [3, 4]])

In [57]:
arr = np.array([5,6])

In [60]:
np.vstack([arr,grid])

array([[5, 6],
       [1, 2],
       [3, 4]])

In [68]:
np.hstack([grid,arr[:, np.newaxis]])

#arr[:,np.newaxis]

array([[1, 2, 5],
       [3, 4, 6]])

In [91]:
x = np.arange(9) 
print(x)
print(np.split(x, 3))
print(np.split(x, [3]))
print(np.split(x, [3,6]))
print(np.split(x, [3,5]))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8])]


In [92]:
# making the case for vectorization

np.random.seed(0)

def compute_reciprocals(values):
  output = np.empty(len(values))

  for i in range(len(values)):
    output[i] = 1.0/values[i]
  return output

In [99]:
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.11111111, 0.5       , 0.14285714, 0.125     , 0.125     ])

In [110]:
big_array = np.random.randint(1,1000, 1000000)

In [106]:
%timeit compute_reciprocals(big_array) # traditional loop based.. takes 2.21 seconds per loop

1 loop, best of 3: 2.21 s per loop


In [111]:
%timeit (1/big_array) #vectorized .. takes 2.67 milli seconds per loop.. 1000 times faster

100 loops, best of 3: 2.67 ms per loop


In [115]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [116]:
x

array([0, 1, 2, 3, 4])

In [117]:
np.add.reduce(x) #interesting mapreduce function right here.. maybe not map.. but reduce definitely.

10

In [118]:
np.multiply.reduce(x)

0

In [119]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10])

In [120]:
np.multiply.accumulate(x)

array([0, 0, 0, 0, 0])

In [121]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [123]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [125]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 3: 1.54 s per loop
100 loops, best of 3: 6.76 ms per loop


In [126]:
%timeit min(big_array)
%timeit np.min(big_array)

1 loop, best of 3: 1.15 s per loop
100 loops, best of 3: 6.78 ms per loop


In [131]:
!head -4 https://github.com/amit1476/myUbuntuRep/blob/master/presidents.csv

head: cannot open 'https://github.com/amit1476/myUbuntuRep/blob/master/presidents.csv' for reading: No such file or directory


In [128]:
!pwd

/content


In [129]:
!ls

sample_data
