<a href="https://colab.research.google.com/github/amit1476/myUbuntuRep/blob/master/pyDS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%timeit sum(range(100))

1000000 loops, best of 3: 871 ns per loop


In [ ]:
%%timeit
total = 0
for i in range(1000):
    for j in range(1000):
        total += i * (-1) ** j

1 loop, best of 3: 321 ms per loop


In [ ]:
import random
L = [random.random() for i in range(100000)]
%timeit L.sort()

The slowest run took 26.64 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.27 ms per loop


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.18.5'

In [ ]:
np?

In [ ]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(l)

list

In [ ]:
type(l[0])

int

In [ ]:
l1 = list([1,2,3,'amit'])

In [ ]:
l1

[1, 2, 3, 'amit']

In [ ]:
type(l1[0])

int

In [ ]:
type(l1[3])

str

In [ ]:
l2 = [str(c) for c in l1]
l2

['1', '2', '3', 'amit']

In [ ]:
[type(item) for item in l1]

[int, int, int, str]

In [ ]:
import array as ar
A = ar.array('i', l)

In [ ]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(A)

array.array

In [ ]:
n1 = np.array(l, dtype='float32')
n1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
#np.array(
[range(i,i+3) for i in [2,3,4]]
#)

[range(2, 5), range(3, 6), range(4, 7)]

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes


In [ ]:
x2[0,1]

5

In [ ]:
x2[0,1] = 12
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[0,1] = 12.5224
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2,]

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8]])

In [ ]:
x2[:2,::3]

array([[3, 4],
       [7, 8]])

In [ ]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2, 12,  3]])

In [ ]:
x2

array([[ 3, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[0,:] # or x2[0]

array([ 3, 12,  2,  4])

In [ ]:
x2_sub = x2[:2,:2]
x2_sub

array([[ 3, 12],
       [ 7,  6]])

In [ ]:
x2_sub[0,0] = 100

In [ ]:
x2_sub

array([[100,  12],
       [  7,   6]])

In [ ]:
x2

array([[100,  12,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [ ]:
x2_sub_copy = x2_sub.copy()
x2_sub_copy

array([[100,  12],
       [  7,   6]])

In [ ]:
x2_sub_copy[0,0]= 20
x2_sub_copy

array([[20, 12],
       [ 7,  6]])

In [ ]:
x2_sub

array([[100,  12],
       [  7,   6]])